name: Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true

    name: Deploy to dev server

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_dev_server }}
          username: ${{ secrets.ftp_dev_username }}
          password: ${{ secrets.ftp_dev_password }}
